### ISSUE TITLE
OpenTSDB 2.3.0  Exception

### ISSUE THREAD

**Issue by JohnOmernik** [mapr-demos/opentsdb-maprdb-install#5]
It looks like OpenTSDB 2.3.0 is looking for something that is only found in Asyncbase 1.7 Since I am running MapR 5.2.1, the included MapR Asyncbase is 1.6.0-mapr-1503 and the asynchbase that comes with 2.3.0 is 1.7.2.

In the documentation for 2.3.0 there is this:

http://opentsdb.github.io/asynchbase/docs/build/html/configuration.html

Which talks about the new config class, so this is likely the issue. (I think)

What is the last version of OpenTSDB known to work with MapR? What would it take for MapR's library to catch up to the 1.7 line?

Thanks!

## ls of /usr/share/opentsdb/lib/async*

root@d0681df07325:/usr/share/opentsdb/lib# ls asynchbase*
asynchbase-1.6.0-mapr-1503.jar  asynchbase-1.7.2.jar-old

## Exception

Exception in thread "main" java.lang.RuntimeException: Initialization failed
	at net.opentsdb.tools.TSDMain.main(TSDMain.java:237)
Caused by: java.lang.NoClassDefFoundError: org/hbase/async/Config
	at net.opentsdb.core.TSDB.<init>(TSDB.java:163)
	at net.opentsdb.core.TSDB.<init>(TSDB.java:252)
	at net.opentsdb.tools.TSDMain.main(TSDMain.java:185)
Caused by: java.lang.ClassNotFoundException: org.hbase.async.Config
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

**Comment by JohnOmernik** [comment]
I found

http://repository.mapr.com/nexus/content/groups/mapr-public/org/hbase/asynchbase/1.7.0-mapr-1607/asynchbase-1.7.0-mapr-1607.jar

Gonna see if I can squeeze that in...

**Comment by JohnOmernik** [comment]
Managed to work the MapR 1.7.0 Async library into the lib folder, 

Now I am getting a different error, but it doesn't appear to be "dying" so I am trying to figure out if it's working... 

## New Exception
Exception in thread "main" java.lang.RuntimeException: Initialization failed
	at net.opentsdb.tools.TSDMain.main(TSDMain.java:237)
Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
	at org.hbase.async.HBaseClient.<init>(HBaseClient.java:566)
	at org.hbase.async.HBaseClient.<init>(HBaseClient.java:654)
	at org.hbase.async.HBaseClient.<init>(HBaseClient.java:616)
	at net.opentsdb.core.TSDB.<init>(TSDB.java:175)
	at net.opentsdb.core.TSDB.<init>(TSDB.java:252)
	at net.opentsdb.tools.TSDMain.main(TSDMain.java:185)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

**Comment by ntirupattur** [comment]
Did you try installing mapr-opentsbd package ? This comes with asynchbase 1.7

**Comment by JohnOmernik** [comment]
I was able to add the 1.7 directly from the link, the other issue (I now opened) was also an issue in that HADOOP_HOME was set based on first directory, and I need it to use hadoop-2.7.0  I got it working with 1.7 and HADOOP_HOME using hadoop2.7.0 now. Thanks!
